# Workflow name
name: Metrics

# Trigger workflow on schedule, workflow dispatch, or push events
on:
  schedule:
    - cron: '0 * * * *' # Run every hour
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  github-metrics:
    # Run workflow on ubuntu-latest environment
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Authentication token
          token: ${{ secrets.METRICS_TOKEN }}
          # GitHub username
          user: michaeljymsgutierrez
          # Template and base settings
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Manila

          # Follow-up plugin settings
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: user
          plugin_followup_indepth: yes

          # Habits plugin settings
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 10%

          # Repositories plugin settings
          plugin_repositories: yes
          plugin_repositories_order: pinned, featured, starred, random
          plugin_repositories_pinned: 6
