name: Metrics
on:
  schedule: [{ cron: '0 * * * *' }]
  workflow_dispatch:
  push: { branches: ['master', 'main'] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_languages: yes
          plugin_stargazers: yes
          plugin_followup: yes
          plugin_stackoverflow: no
          plugin_achievements: yes
          plugin_achievements_ignored: influencer, follower, maintainer, contributor, explorer, octonaut
          plugin_gists: yes
          plugin_lines: yes
          plugin_stars: yes
          plugin_stars_limit: 3
          plugin_traffic: yes
